import type { Session } from "../../types/Session";

export const testSessions: Session[] = [
    {
        id: 1,
        stressLevel: null,
        headache: 1,
        sleepQuality: 3,
        breathingProblems: 1,
        noiseLevel: 4,
        livingConditions: 3,
        safety: 5,
        basicNeeds: 4,
        academicPerformance: 3,
        studyLoad: 2,
        teacherStudentRelationship: 4,
        futureCareerConcerns: 3,
        socialSupport: 2,
        peerPressure: 3,
        extracurricularActivities: 4,
        bullying: 1
    },
    {
        id: 2,
        stressLevel: 2,
        headache: 1,
        sleepQuality: 3,
        breathingProblems: 1,
        noiseLevel: 4,
        livingConditions: 3,
        safety: 5,
        basicNeeds: 4,
        academicPerformance: 3,
        studyLoad: 2,
        teacherStudentRelationship: 4,
        futureCareerConcerns: 3,
        socialSupport: 2,
        peerPressure: 3,
        extracurricularActivities: 4,
        bullying: 1
    },
    {
        id: 3,
        stressLevel: 2,
        headache: 1,
        sleepQuality: 3,
        breathingProblems: 1,
        noiseLevel: 4,
        livingConditions: 3,
        safety: 5,
        basicNeeds: 4,
        academicPerformance: 3,
        studyLoad: 2,
        teacherStudentRelationship: 4,
        futureCareerConcerns: 3,
        socialSupport: 2,
        peerPressure: 3,
        extracurricularActivities: 4,
        bullying: 1
    },
    {
        id: 4,
        stressLevel: 2,
        headache: 1,
        sleepQuality: 3,
        breathingProblems: 1,
        noiseLevel: 4,
        livingConditions: 3,
        safety: 5,
        basicNeeds: 4,
        academicPerformance: 3,
        studyLoad: 2,
        teacherStudentRelationship: 4,
        futureCareerConcerns: 3,
        socialSupport: 2,
        peerPressure: 3,
        extracurricularActivities: 4,
        bullying: 1
    }
]